name: "Windows Build"
on: push
permissions:
    contents: read
jobs:
    build:
        name: "Windows Build Job"
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v2
              with:
                submodules: true
            # Install latest CMake.
            - uses: lukka/get-cmake@latest
                # Restore from cache the previously built ports. If cache-miss, download and build vcpkg (aka "bootstrap vcpkg").
            - name: Restore from cache and install vcpkg
              # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
              uses: lukka/run-vcpkg@v7
              with:
                setupOnly: true
            - run: |
                $VCPKG_ROOT/vcpkg install wxwidgets:windows-x64 nlohmann-json:windows-x64 civetweb:windows-x64
              shell: bash
            - run: |
                cmake . -DCMAKE_BUILD_TYPE=Release "-DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" && cmake --build .
              shell: bash
            - name: Archive built executable
              uses: actions/upload-artifact@v2
              with:
                name: QuickOpen.exe
                path: cmake_build_release/QuickOpen.exe